### ISSUE TITLE
Perl memory leak with Net::SNMP gettable() method

### ISSUE THREAD

**Issue by fellowsr** [net-snmp/net-snmp#135]
# Tested on - 
 * net-snmp 5.5 on Oracle Linux 6, vendor package
 * net-snmp 5.7.3 on Raspian 4.19.118-v7+, vendor package
 * net-snmp 5.8 on Ubuntu 20.04 LTS, build from source.
# Replication steps
Run the perl script below and monitor memory usage with `top` or `htop`.

```perl
#!/usr/bin/perl
use strict;
use warnings;
use SNMP;
my $session = SNMP::Session->new(
     DestHost  => '127.0.0.1',
     Version   => 2,
     Community => 'secret'
);
for ( 0 .. 20000 ) {
     my $if = $session->gettable('ifTable');
}
__END__
```
htop output a few seconds apart -
```
   PID USER      PRI  NI  VIRT   RES   SHR S CPU% MEM%   TIME+  Command
  83596 fellowsr   20   0 21504 16776  6548 R 84.1  0.8  0:06.71 perl ./gettable.pl
```
later -
```
    PID USER      PRI  NI  VIRT   RES   SHR S CPU% MEM%   TIME+  Command
  83596 fellowsr   20   0 46608 41880  6548 R 85.2  2.1  0:43.28 perl ./gettable.pl
```
I've written similar test scripts for other methods defined in SNMP.pm https://metacpan.org/pod/SNMP

* get() - no leak.
* fget() - no leak.
* fgetnext() - no leak.
* getnext() - no leak.
* gettable with various calls -
  * `$session->gettable('ifTable')` - **leaks**.
  * `$session->gettable('ifTable')` - **leaks.**
  * `$session->gettable('ifTable',callback => \&my_cb);` **leaks**
  * `$session->gettable('ifTable', column => [ 'ifInOctets' ]);` **leaks**
  * `$session->gettable('ifTable',nogetbulk =>1);` **leaks**
  * `$session->gettable( 'ifTable', noindexes => 1 );` **leaks**
* trap - no leak.

# Edit 1
Happy to run valgrind or other tools to attempt to tie this down. Just tell me what you need me to run. I've been trying to do this myself but I've not done any prior work with XS code, so the results don't make a lot of sense to me.

# Edit 2
Had more success with valgrind I think?

```bash
$ PERL_DEBUG=1 PERL_VALGRIND=1 PERL_DESTRUCT_LEVEL=2 valgrind --leak-check=full --show-leak-kinds=all debugperl ./gettable.pl 20 > 20.txt 2>&1
$ PERL_DEBUG=1 PERL_VALGRIND=1 PERL_DESTRUCT_LEVEL=2 valgrind --leak-check=full --show-leak-kinds=all debugperl ./gettable.pl 5 > 5.txt 2>&1
```
5 iterations round the loop
[5.txt](https://github.com/net-snmp/net-snmp/files/4788371/5.txt)
20 iterations round the loop
[20.txt](https://github.com/net-snmp/net-snmp/files/4788373/20.txt)

# Edit 3
```bash
$ TEST_LEAKTRACE=-verbose debugperl -MTest::LeakTrace::Script ./gettable.pl 1 > test_leaktrace1.txt 2>&1 
$ TEST_LEAKTRACE=-verbose debugperl -MTest::LeakTrace::Script ./gettable.pl 2 > test_leaktrace2.txt 2>&1 
$ TEST_LEAKTRACE=-verbose debugperl -MTest::LeakTrace::Script ./gettable.pl 20 > test_leaktrace20.txt 2>&1 
$ TEST_LEAKTRACE=-simple debugperl -MTest::LeakTrace::Script ./gettable.pl 20 > test_leaktrace20_simple.txt 2>&1 
$ TEST_LEAKTRACE=-simple debugperl -MTest::LeakTrace::Script ./gettable.pl 40 > test_leaktrace40_simple.txt 2>&1 
```
[test_leaktrace40_simple.txt](https://github.com/net-snmp/net-snmp/files/4794958/test_leaktrace40_simple.txt)
[test_leaktrace1.txt](https://github.com/net-snmp/net-snmp/files/4794959/test_leaktrace1.txt)
[test_leaktrace20.txt](https://github.com/net-snmp/net-snmp/files/4794960/test_leaktrace20.txt)
[test_leaktrace20_simple.txt](https://github.com/net-snmp/net-snmp/files/4794961/test_leaktrace20_simple.txt)

Looking at the frequency of line number mentions in the *simple* files

* 1
```
$ perl -ne 'BEGIN { my %count;} if($_ =~ m/ line (\d+)\./) { ++$count{$1};} END { for my $k (sort keys(%count)){ print "$k\t$count{$k}\n";}}' test_leaktrace1_simple
105	1
106	3
1092	1
1098	1
1387	7
1390	24
15	1
239	2
426	109
512	1
60	1
618	3
74	8
75	2
887	3
893	2
924	1
```
* 2
```
$ perl -ne 'BEGIN { my %count;} if($_ =~ m/ line (\d+)\./) { ++$count{$1};} END { for my $k (sort keys(%count)){ print "$k\t$count{$k}\n";}}' test_leaktrace2_simple
105	1
106	3
1092	1
1098	1
1387	7
1390	88
15	1
239	2
426	109
512	1
60	1
618	3
74	8
75	2
887	3
893	2
924	1
```
*  20
```
$ perl -ne 'BEGIN { my %count;} if($_ =~ m/ line (\d+)\./) { ++$count{$1};} END { for my $k (sort keys(%count)){ print "$k\t$count{$k}\n";}}' test_leaktrace20_simple
105	1
106	3
1092	1
1098	1
1387	7
1390	1240
15	1
239	2
426	109
512	1
60	1
618	3
74	8
75	2
887	3
893	2
924	1
```
* 40 
```
$ perl -ne 'BEGIN { my %count;} if($_ =~ m/ line (\d+)\./) { ++$count{$1};} END { for my $k (sort keys(%count)){ print "$k\t$count{$k}\n";}}' test_leaktrace40_simple
105	1
106	3
1092	1
1098	1
1387	7
1390	2520
15	1
239	2
426	109
512	1
60	1
618	3
74	8
75	2
887	3
893	2
924	1
```

This seems to indicate the leak is in `SNMP.pm` :-
```perl
package SNMP::MIB;

sub TIEHASH {
    bless {};
}

sub FETCH {
    my $this = shift;
    my $key = shift;

    if (!defined $this->{$key}) {
	tie(%{$this->{$key}}, 'SNMP::MIB::NODE', $key) or return undef;
    }
    $this->{$key};    # <<< leak indicated here
}
```

**Comment by hardaker** [comment]
I suspect that there is likely multiple places that a similar leak might exist.  We'll have to dig.

**Comment by PavelTrushkin** [comment]
I can explain this problem. 

perl/SNMP/SNMP.xs:

```c
void
snmp_session_DESTROY(sess_ptr)
        void *sess_ptr
```

in this block sess_ptr MUST be defined as SnmpSession *

```c
void
snmp_session_DESTROY(sess_ptr)
        SnmpSession *sess_ptr
```

here is a results of conversion .xs to .c for this code

for void *

```c
void *  sess_ptr = INT2PTR(void *,SvIV(ST(0)))
```

for SnmpSession *

```c
       SnmpSession *   sess_ptr;
   
        if (SvROK(ST(0))) {
            IV tmp = SvIV((SV*)SvRV(ST(0)));
            sess_ptr = INT2PTR(SnmpSession *,tmp);
        }
        else
            Perl_croak_nocontext("%s: %s is not a reference",
                        "SnmpSessionPtr::DESTROY",
                        "sess_ptr")
```

this is a very very bad bug and a big problem

**Comment by fellowsr** [comment]
I've made the suggested change to my local version

```perl
diff --git a/perl/SNMP/SNMP.xs b/perl/SNMP/SNMP.xs
index 2e2c0fafe..dca8b08bb 100644
--- a/perl/SNMP/SNMP.xs
+++ b/perl/SNMP/SNMP.xs
@@ -5434,7 +5434,8 @@ MODULE = SNMP     PACKAGE = SnmpSessionPtr        PREFIX = snmp_session_
 
 void
 snmp_session_DESTROY(sess_ptr)
-       void *sess_ptr
+       SnmpSession *sess_ptr
        CODE:
        {
        if(sess_ptr != NULL)
```

Re-running the previous `gettable.pl` test script I still see memory increasing over time.

**Comment by PavelTrushkin** [comment]
Could you try this commit https://github.com/PavelTrushkin/net-snmp/commit/9e96f06b253b90c13f7223110e5d78b307a5a9ff

it is fixed gettable leaks for me

i recommend to use this (new method from my patch)

SNMP::freeMib;

at end of your test perl script, it will decrease total number of messages from valgrind

**Comment by PavelTrushkin** [comment]
i have pushed new PR #179 covering this problem

**Comment by bvanassche** [comment]
Please reopen this bug report if it needs further attention.

**Comment by fellowsr** [comment]
> Please reopen this bug report if it needs further attention.

I've cloned from the current repo. Still seeing the leak :( can you please re open and continue the investigation.

**Comment by bvanassche** [comment]
@fellowsr, which branch has been tested? V5-9-patches or master?

**Comment by fellowsr** [comment]
I tried master, built with `./configure` , `make` and passes `make test` & `sudo make install`.
I also tried branch V5-9-patches, this appeared to fail at `make test`. I did not capture the test failure. I will rebuild both branches again tomorrow, and update the results here.

**Comment by fellowsr** [comment]
updated to current master b8f4e856b14eb3b1d12083f9f50299a16b8c36b3. 
```shell
make clean
./configure
make
make test
```
Test passes.
```shell
sudo make install
```
running my test script and monitoring with htop, memory use for process starts around 0.6% and grows to 2.3% in ~5 minutes.

Running for 20 repeats with
```shell
$ TEST_LEAKTRACE=-verbose debugperl -MTest::LeakTrace::Script ./gettable.pl 20  2>20200930_20.txt
```
[20200930_20.txt](https://github.com/net-snmp/net-snmp/files/5308153/20200930_20.txt)

**Comment by fellowsr** [comment]
Switched to V5-9-patches 4d686f50d165f6b2b8fc79c9ae8f0a5702644fd8, and built as above. Memory leak still present from htop view.

**Comment by bvanassche** [comment]
The memory leak fixes have been backported to the V5-9-patches branch. Please retest.

**Comment by fellowsr** [comment]
In branch V5-9-patches updated to b1569c31514bf76fceb93f80c8b844101ee55e3a and rebuilt and installed. Leak still present as seen from `htop`'s  __MEM%__ number .
